# Generated by Django 5.1.3 on 2024-11-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mediafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mediafile/')),
            ],
        ),
        migrations.CreateModel(
            name='mediafiledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('extension', models.CharField(max_length=10)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='myapp.mediafile')),
            ],
        ),
    ]
