# Generated by Django 5.1.3 on 2024-11-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_data', models.JSONField()),
                ('after_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('media_file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.mediafiledata')),
            ],
        ),
    ]
