# Generated by Django 5.1.3 on 2024-12-03 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_logs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mediafile_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediafiledata',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mediafiledata_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
